// Static image list for GitHub Pages deployment
// This file contains the list of all available images
window.IMAGES_DATA = {
    real: [
        { file: "(1).jpg", type: "real" },
        { file: "(2).jpg", type: "real" },
        { file: "(3).jpg", type: "real" },
        { file: "(4).jpg", type: "real" },
        { file: "(5).jpg", type: "real" },
        { file: "(6).jpg", type: "real" },
        { file: "(7).jpg", type: "real" },
        { file: "(8).jpg", type: "real" },
        { file: "(9).jpg", type: "real" },
        { file: "(10).jpg", type: "real" },
        { file: "(11).jpg", type: "real" },
        { file: "(12).jpg", type: "real" },
        { file: "(13).jpg", type: "real" },
        { file: "(14).jpg", type: "real" },
        { file: "(15).jpg", type: "real" },
        { file: "(16).jpg", type: "real" },
        { file: "(17).jpg", type: "real" },
        { file: "(18).jpg", type: "real" },
        { file: "(19).jpg", type: "real" },
        { file: "(20).jpg", type: "real" }
    ],
    fake: [
        { file: "(1).jpg", type: "fake" },
        { file: "(2).jpg", type: "fake" },
        { file: "(3).jpg", type: "fake" },
        { file: "(4).jpg", type: "fake" },
        { file: "(5).jpg", type: "fake" },
        { file: "(6).jpg", type: "fake" },
        { file: "(7).jpg", type: "fake" },
        { file: "(8).jpg", type: "fake" },
        { file: "(9).jpg", type: "fake" },
        { file: "(10).jpg", type: "fake" },
        { file: "(11).jpg", type: "fake" },
        { file: "(12).jpg", type: "fake" },
        { file: "(13).jpg", type: "fake" },
        { file: "(14).jpg", type: "fake" },
        { file: "(15).jpg", type: "fake" },
        { file: "(16).jpg", type: "fake" },
        { file: "(17).jpg", type: "fake" },
        { file: "(18).jpg", type: "fake" },
        { file: "(19).jpg", type: "fake" },
        { file: "(20).jpg", type: "fake" },
        { file: "(21).jpg", type: "fake" },
        { file: "(22).jpg", type: "fake" }
    ]
};